---
name: Apache2 Basic PHP Server
version: 1.0.1
slug: apache2-basic-php
description: Webserver with some basic PHP Modules
url: https://github.com/realpasha/hassio-addons/tree/main/apache2-basic-php
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
webui: http://[HOST]:[PORT:80]
map:
  - ssl:rw
  - media:rw
  - share:rw
ingress: true
init: false
panel_icon: mdi:web-box
options:
  document_root: /share/htdocs
  php_ini: default
  default_conf: default
  default_ssl_conf: default
  website_name: null
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
  init_commands: []
schema:
  document_root: str
  php_ini: str
  default_conf: str
  default_ssl_conf: str
  website_name: str
  username: str?
  password: password?
  ssl: bool
  certfile: str
  keyfile: str
  init_commands:
    - str?
ports:
  80/tcp: 80
  443/tcp: 8324
ports_description:
  80/tcp: Web interface http
  443/tcp: SSL Web interface